# docker-compose.yml

version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"  # Maps container port 5000 to host port 5000
    volumes:
      - .:/app  # Mount the current directory to the app directory in the container
    environment:
      - FLASK_ENV=development  # Set environment variables
    command: python app/main.py  # Run the Flask app
