# .github/workflows/ci.yml

name: Python CI with Docker

# Trigger the workflow on pushes and pull requests to the 'master' branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 4: Build the Docker container for the app
      - name: Build the Docker image
        run: docker build -t my-flask-app .

      # Step 5: Run the container with Docker Compose
      - name: Run Docker Compose
        run: docker-compose up -d --build

      # Step 6: Run tests inside the Docker container
      - name: Run tests in the container
        run: |
          docker-compose exec web pytest

      # Step 7: Stop and remove Docker containers after tests
      - name: Teardown Docker Compose
        run: docker-compose down
